import { Dimensions, Platform } from 'react-native';
const _size = (((Dimensions.get('window').height) + (Dimensions.get('window').width)) / 10);
export default {
    Fonts: {
        'regular': require('../assets/Fonts/inter/Inter-Black.ttf'),
        'medium': require("../assets/Fonts/inter/Inter-Bold.ttf"),
        'bold': require('../assets/Fonts/inter/Inter-ExtraBold.ttf'),
        'light': require('../assets/Fonts/inter/Inter-ExtraLight.ttf'),
        'ulLight': require('../assets/Fonts/inter/Inter-Light.ttf'),
        'black': require('../assets/Fonts/inter/Inter-Medium.ttf'),
        'demiBold': require('../assets/Fonts/inter/Inter-Regular.ttf'),
        'exBold': require('../assets/Fonts/inter/Inter-Thin.ttf'),
        'exLight': require('../assets/Fonts/inter/Inter-SemiBold.ttf'),
        // 'thin': require('@Assets/Fonts/Dana/Dana-FaNum-Thin.ttf'),
        // 'ulBold': require('@Assets/Fonts/Dana/Dana-FaNum-UltraBold.ttf'),
        // 'iconlybold': require('@Assets/FontIcons/Iconly/iconlybold.ttf'),
        // 'iconlybroken': require('@Assets/FontIcons/Iconly/iconlybroken.ttf'),
        // 'iconlybulk': require('@Assets/FontIcons/Iconly/iconlybulk.ttf'),
        // 'iconlylight': require('@Assets/FontIcons/Iconly/iconlylight.ttf'),
        // 'IconlyOther': require('@Assets/FontIcons/Iconly/IconlyOther.ttf'),
    },
    Size: {
        130: Math.round(_size / 0.85),
        120: Math.round(_size),
        100: Math.round(_size / 1.15),
        90: Math.round(_size / 1.3),
        80: Math.round(_size / 1.5),
        70: Math.round(_size / 1.7),
        60: Math.round(_size / 2),
        50: Math.round(_size / 2.4),
        45: Math.round(_size / 2.5),
        40: Math.round(_size / 3),
        38: Math.round(_size / 3.2),
        35: Math.round(_size / 3.5),
        30: Math.round(_size / 4),
        27: Math.round(_size / 4.5),
        24: Math.round(_size / 5),
        23: Math.round(_size / 5.3),
        21: Math.round(_size / 6),
        19: Math.round(_size / 6.5),
        17: Math.round(_size / 7),
        15: Math.round(_size / 8),
        14: Math.round(_size / 9),
        13: Math.round(_size / 9.5),
        12: Math.round(_size / 10),
        11: Math.round(_size / 11),
        10: Math.round(_size / 12),
        9: Math.round(_size / 13),
        7: Math.round(_size / 15),
        6: Math.round(_size / 19),
        5: Math.round(_size / 24),
    },
    Width: Math.round(Dimensions.get('window').width),
    Height: Math.round(Dimensions.get('window').height),
    IsWeb: Platform.OS == "web" ? true : false,
};
